version: "3"
services:
  front_end_app:
    build:
        context: front_end_app
        dockerfile: Dockerfile
    command: python3 front_end_app.py
    depends_on:
        - api
    container_name: front_end_app
    ports:
      - 5000:5000
  api:
    build:
        context: api
        dockerfile: Dockerfile
    command: python3 api.py
    container_name: api
    ports:
      - 8000:8000
